### ISSUE TITLE
Package 'plasma5-applets-redshift-control' missing

### ISSUE THREAD

**Issue by pottink** [BlackIkeEagle/archlinux-reinstall#7]
https://github.com/BlackIkeEagle/archlinux-reinstall/blob/c5e7ab6471bce3bc5aff3ce4a04f9fcdd9f79649/plasma-desktop.packages#L62

Package seems removed / missing:

`plasma5-applets-redshift-control`

**Comment by BlackIkeEagle** [comment]
Yes, its no longer needed, plasma desktop now has built-in color control

see: https://kde.org/announcements/plasma-5.17.0.php search for 'Night Color'
